import { createRequire } from "node:module";
import assert from "node:assert/strict";
import { mkdir, writeFile } from "node:fs/promises";
const require = createRequire(import.meta.url);
const { chromium } = require("playwright");
const url = process.env.STRATEGY_QA_URL ?? "http://localhost:8791";
if (!/^http:\/\/(localhost|127\.0\.0\.1):\d+$/.test(url)) throw new Error("Smoke tests use anonymous local data only");
const output = process.env.STRATEGY_QA_OUTPUT ?? "/tmp/fordays-strategy-browser-qa";
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ headless: true, channel: "chrome" });
const errors = [];
try {
  const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
  page.on("pageerror", (e) => errors.push(e.message));
  await page.goto(`${url}/simulator`);
  await page.getByRole("heading", { name: "TRDへの組織をつくる" }).waitFor();
  const ready = () => page.locator('.canvas-outcome[aria-busy="false"]').waitFor({ timeout: 120000 });
  await ready();
  await page.getByRole("button", { name: "前提・詳細設定", exact: true }).click();
  const planName = `ブラウザ確認 ${Date.now()}`;
  await page.getByLabel("計画名", { exact: true }).fill(planName);
  await page.getByLabel("計算年数（期限ではありません）").fill("1");
  await page.getByRole("button", { name: "この前提で計算して組織に戻る", exact: true }).click();
  await ready();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, "mobile document must not overflow horizontally");
  await page.getByRole("button", { name: "＋ 人・チームを追加", exact: true }).click();
  await page.getByRole("button", { name: "20人一括", exact: true }).click();
  await ready();
  await page.getByRole("button", { name: "試算チーム 追加予定チーム · 配置変更", exact: true }).click();
  assert.equal(await page.getByRole("spinbutton", { name: "一緒に加入する人数", exact: true }).inputValue(), "19");
  await page.getByRole("button", { name: "同じ経過時間", exact: true }).click();
  await page.getByRole("spinbutton", { name: "開始からの月数", exact: true }).fill("12");
  await page.getByRole("button", { name: "同じくらいの人数", exact: true }).click();
  await page.getByLabel("人数の目安", { exact: true }).selectOption("100");
  await page.locator(".canvas-outcome .studio-income summary").click();
  await page.screenshot({ path: `${output}/mobile-result.png`, fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, "results must not overflow horizontally");
  await page.getByRole("button", { name: "別案として保存", exact: true }).click();
  await page.getByText("入力・出発点・結果を新しい版として保存しました", { exact: true }).waitFor();
  await page.reload();
  await ready();
  await page.getByRole("button", { name: "保存したプラン", exact: true }).click();
  await page.locator("section.panel").filter({ has: page.getByRole("heading", { name: planName, exact: true }) }).getByRole("button", { name: "プランを開く", exact: true }).click();
  await page.getByText("保存時の出発点と結果を表示しています", { exact: true }).waitFor();
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: `${output}/desktop-studio.png`, fullPage: true });
  await page.goto(`${url}/forecast`);
  await page.waitForURL(`${url}/simulator`);
  await page.getByRole("heading", { name: "TRDへの組織をつくる" }).waitFor();
  const started = Date.now();
  await ready();
  const tenYearMilliseconds = Date.now() - started;
  const cacheLeaks = await page.evaluate(async () => {
    const keys = await caches.keys(); const leaks = [];
    for (const key of keys) { const cache = await caches.open(key); for (const r of await cache.keys()) if (new URL(r.url).pathname.startsWith("/api/")) leaks.push(r.url); }
    return leaks;
  });
  assert.deepEqual(cacheLeaks, []);
  assert.deepEqual(errors, []);
  const report = { success: true, widths: [390, 1440], flows: ["calculate", "20-person template", "approximate-count comparison", "elapsed-time comparison", "breakdown", "save", "restore", "forecast redirect", "ten-year browser-worker run"], tenYearMilliseconds, apiCacheEntries: 0, errors };
  await writeFile(`${output}/report.json`, JSON.stringify(report, null, 2));
  console.log(JSON.stringify(report));
} finally { await browser.close(); }
