import { NavLink } from "react-router-dom";
import "./quick-guide.css";

function Screen({ file, alt, caption }: { file: string; alt: string; caption: string }) {
  return <figure className="guide-screen"><a href={`/guide/${file}.png`} target="_blank" rel="noreferrer" aria-label={`${alt}（画像を拡大・別タブ）`}><img src={`/guide/${file}.png`} alt={alt} loading="lazy" width="1265" height="712" /></a><figcaption>{caption} <span>画像をタップすると拡大できます。</span></figcaption></figure>;
}

export default function QuickGuide() {
  return <article className="quick-guide">
    <header className="guide-hero"><p className="guide-eyebrow">STRATEGY STUDIO · 3分ガイド</p><h1>配置を変えたら、<br />未来はどう変わる？</h1><p>同じTRDでも月額が違う。同じ人数でも、かかる時間が違う。<br />その違いを、組織を動かして見比べるためのアプリです。</p><NavLink className="guide-start" to="/simulator">試算画面を開く →</NavLink><p className="guide-example">掲載画面は架空のサンプルです。金額・期間は操作例であり、あなたの試算結果ではありません。</p></header>
    <nav className="guide-index" aria-label="操作ガイドの目次"><a href="#guide-move">01 配置を変える</a><a href="#guide-compare">02 比べる</a><a href="#guide-money">03 内訳を見る</a><a href="#guide-save">04 保存する</a></nav>
    <section className="guide-section"><p className="guide-eyebrow">まずはここだけ</p><h2>見るのは「月額・時間・人数」</h2><div className="guide-three"><div><b>月額</b><p>一時報酬を除いた<br />「世帯の継続月額」</p></div><div><b>時間</b><p>目標タイトルに<br />到達するまでの期間</p></div><div><b>人数</b><p>その時点の<br />組織ID数</p></div></div><p>「戦略試算」を開くと、現在の組織をもとに計算が始まります。上部の<strong>集計</strong>で、自分・パートナー・所有サブのどこまでを含めるか確認しましょう。</p><Screen file="01-overview" alt="左に操作する組織、右に継続月額と到達期間を表示した試算画面" caption="パソコンは組織と結果が横並び。スマホは結果と組織が縦に並びます。" /></section>
    <section className="guide-section" id="guide-move"><p className="guide-eyebrow">01 · 動かす</p><h2>ひとつのチームを、別の配下へ</h2><ol className="guide-steps"><li><strong>動かしたい人を選ぶ。</strong><span>名前をクリック・タップすると、設定が開きます。</span></li><li><strong>「移動先」を選び、「ここへ移動」。</strong><span>パソコンなら、名前の横の「⠿」を配置先へドラッグしてもOK。</span></li><li><strong>再計算が終わったら、月額の差を見る。</strong><span>その人の配下もまとめて動きます。「元に戻す」で直前の配置へ戻せます。</span></li></ol><Screen file="02-move" alt="メンバーを選び、配置先を選択して「ここへ移動」を押す画面" caption="移動するのは試算上の配置だけです。紹介者や公式の登録は変わりません。" /><details className="guide-tip"><summary>まだ加入していない人を追加したい</summary><p>「＋ 人・チームを追加」から「1人」「20人一括」「リーダー＋10人」などを選びます。追加したチームをタップすると、人数・開始時期・配置を調整できます。</p><p>「20人一括」はリーダー1名＋同行19名。「リーダー＋10人」は合計11名です。「1人が1人」「3人が3人」は成長前提のひな型として使います。</p></details></section>
    <section className="guide-section" id="guide-compare"><p className="guide-eyebrow">02 · 比べる</p><h2>何を同じにするかで、答えが変わる</h2><p>配置を動かすと、変更前が<strong>案A</strong>、編集中が<strong>案B</strong>になります。「現在の案を比較基準Aに固定」でも基準を選べます。</p><div className="guide-comparisons"><div><h3>同じタイトル</h3><p>どちらもTRDになったとき、<strong>月額はいくら？ 何年かかる？</strong></p></div><div><h3>同じくらいの人数</h3><p>同じ規模まで育ったとき、<strong>どちらが早い？ 月額は？</strong></p><small>人数は目安です。比較欄の実際のID数も確認します。</small></div><div><h3>同じ経過時間</h3><p>たとえば10年後、<strong>人数・タイトル・月額はどう違う？</strong></p><small>「開始からの月数」に120と入力すると10年後です。</small></div></div><Screen file="03-compare" alt="同じ10年・509 IDで、案Aと案Bの継続月額を横並びに比較した画面" caption="この操作例では同じ10年・509 IDでも、配置によって継続月額に2,930円の差が出ています。" /><p className="guide-takeaway">配置だけの違いを知りたいときは、成長・購入などの前提を揃えて比べましょう。</p><details className="guide-tip"><summary>「未到達」と出たら？</summary><p>計算した期間では、目標タイトルの条件が揃っていない状態です。「同じ経過時間」なら途中の結果を比べられます。「TRDまでの不足条件」を開くと、不足内容と「さらに10年先まで計算」を確認できます。</p><p>100・300・500・1,000・1,500・2,000 IDは「途中の成長を見る」の目印です。2,000 ID自体がゴールではありません。</p></details></section>
    <section className="guide-section" id="guide-money"><p className="guide-eyebrow">03 · 金額を読む</p><h2>月額を見る。気になったら内訳を開く</h2><p>結果の「各ID・ボーナス内訳」、比較欄の「この時点の内訳」をタップします。自分・パートナー・各サブIDの取り分を確認できます。</p><dl className="guide-glossary"><div><dt>継続月額</dt><dd>ライン＋ディレクター＋タイトル。一時的なスタート・トレーナーボーナスは含みません。</dd></div><div><dt>ラインのみ</dt><dd>ラインボーナスだけを見たいときの金額です。</dd></div><div><dt>総ボーナス</dt><dd>継続分と一時分を合計した、その月のボーナスです。内訳を開く見出しの金額もこちらです。</dd></div><div><dt>概算受取額</dt><dd>入力した控除・手数料・繰越などを反映した金額です。</dd></div><div><dt>購入費控除後の参考月額</dt><dd>一時報酬・繰越を除き、控除と所有IDの購入費を反映した参考収支です。</dd></div></dl><Screen file="04-breakdown" alt="ライン・継続・一時報酬とID別の5種類のボーナスを展開した画面" caption="上の大きな月額と、内訳見出しの金額が違うのは、一時報酬を含むかどうかの違いです。" /><p className="guide-example">継続月額も、設定した活動・購入・資格の条件が続く場合の目安です。</p></section>
    <section className="guide-section" id="guide-save"><p className="guide-eyebrow">04 · 残す</p><h2>よい案は保存して、あとで見比べる</h2><ol className="guide-steps"><li><strong>「前提・詳細設定」で計画名を付ける。</strong><span>例：「メイン直下案」「サブを挟む案」。変更後は「この前提で計算して組織に戻る」を押します。</span></li><li><strong>「別案として保存」を押す。</strong><span>計算が終わると保存できます。配置を動かしただけでは自動保存されません。</span></li><li><strong>「保存したプラン」から開く。</strong><span>「比較基準Aにする」で保存案を基準にし、別の案を開いて比較できます。</span></li></ol><Screen file="05-saved" alt="保存したプランから「プランを開く」「比較基準Aにする」を選ぶ画面" caption="保存時の入力・出発点・計算結果を、そのまま見返せます。" /><p className="guide-takeaway">まずは「メイン直下案」と「サブを挟む案」の2つを保存すると、違いを見返しやすくなります。</p></section>
    <section className="guide-section guide-shortcuts"><h2>迷ったときの早見表</h2><dl><div><dt>紹介ペース・継続率を変える</dt><dd>前提・詳細設定 → 現在地と成長前提</dd></div><div><dt>パートナーも合算する</dt><dd>前提・詳細設定 → パートナーを選択 → 再計算</dd></div><div><dt>控えめな場合も見たい</dt><dd>上部の成長前提 → 保守・標準・挑戦を切替</dd></div><div><dt>タイトル条件を確認する</dt><dd>その他 → 全タイトル条件</dd></div></dl><NavLink className="guide-start" to="/simulator">配置を動かしてみる →</NavLink></section>
    <footer className="guide-footer">Strategy Studio 2.1 対応 · 2026年9月更新</footer>
  </article>;
}
