import { NavLink } from "react-router-dom";
import "./quick-guide.css";

export default function QuickGuide() {
  return <article className="quick-guide">
    <header className="guide-hero"><p className="guide-eyebrow">STRATEGY STUDIO · 3分ガイド</p><h1>配置を変えたら、<br/>未来はどう変わる？</h1><p>人を動かす。月額とTRDまでの時間を比べる。<br/>時間を動かして、途中の組織も確かめる。</p><NavLink className="guide-start" to="/simulator">試算画面を開く →</NavLink></header>
    <nav className="guide-index" aria-label="操作ガイドの目次"><a href="#guide-move">01 動かす</a><a href="#guide-time">02 時間を見る</a><a href="#guide-money">03 内訳</a><a href="#guide-save">04 保存</a></nav>
    <section className="guide-section" id="guide-move"><p className="guide-eyebrow">01 · 動かす</p><h2>まず、人をひとり動かしてみる</h2><ol className="guide-steps"><li><strong>組織図の名前をタップ。</strong><span>「誰の下に置きますか？」から配置先を選びます。「⠿」を配置先へドラッグしても移動できます。</span></li><li><strong>「ここへ移動して試算」を押す。</strong><span>その人の配下ごと動き、自動で再計算します。</span></li><li><strong>上の月額と到達時期の差を見る。</strong><span>「元に戻す」で直前の配置へ。「↷」でやり直せます。</span></li></ol><p>移動するのは試算の出発点の配置です。公式登録や、既存の紹介者は変わりません。</p><details className="guide-tip"><summary>まだ加入していない人を追加したい</summary><p>「＋ 人・チーム」から選びます。「20人一括」はリーダー1名＋同行19名。「リーダー＋10人」は合計11名です。</p><p>名前を選ぶと、配下のポテンシャルを100・300・500 IDや任意の人数で設定できます。本人を除くチーム全体の上限の目安で、必ず到達する人数ではありません。「まだ加入前」の人は、その時点の人数や報酬に含みません。</p></details></section>
    <section className="guide-section" id="guide-time"><p className="guide-eyebrow">02 · 時間を見る</p><h2>時間スライダーで、同じ月の組織と金額を見る</h2><div className="guide-three"><div><b>月額</b><p>選んだ月の<br/>世帯の継続月額</p></div><div><b>組織</b><p>同じ月の<br/>配置・配下人数</p></div><div><b>タイトル</b><p>同じ月の<br/>各IDの判定結果</p></div></div><p>「現在」で出発点へ。「TRD到達」で到達月へ戻ります。到達していない場合は計算期間の最後まで確認できます。TRDまでの所要時間は、スライダーを動かしても同じ計画の到達時期を表示します。</p><p>名前の <b>(100)</b> は、本人を除く配下全体の在籍ID数です。休止中も含む在籍人数と、購入のある稼働人数は別表示です。親の数には子の配下も含まれるので、親子の数字を足しません。</p><details className="guide-tip"><summary>同じTRD・同じ人数で比較したい</summary><p>「その他 → 変更前と詳しく比べる」を開きます。同じTRD、同じ人数、同じ時点に揃えて比較できます。人数の節目は「その他 → 人数の節目へ移動」から確認します。</p></details></section>
    <section className="guide-section" id="guide-money"><p className="guide-eyebrow">03 · 金額を読む</p><h2>「金額の内訳」で、一時分と毎月分を分ける</h2><dl className="guide-glossary"><div><dt>継続月額</dt><dd>ライン＋ディレクター＋タイトル。一時的なスタート・トレーナーボーナスを除きます。</dd></div><div><dt>うちラインボーナス</dt><dd>継続月額のうち、ラインボーナスだけの金額です。</dd></div><div><dt>総ボーナス</dt><dd>その月の継続分と一時分の合計です。</dd></div><div><dt>購入費控除後の参考月額</dt><dd>継続分から入力した控除と所有IDの購入費を引いた目安です。</dd></div></dl><p>「ID別・5種類のボーナス」を開くと、自分・パートナー・それぞれのサブの取り分を確認できます。金額は選択した前提が続く場合の試算です。</p></section>
    <section className="guide-section"><h2>人数は増えたのに、タイトルが上がらないとき</h2><p>「その他 → TRDまでの不足条件」で確認します。DRには人数だけでなく、本人のB・Gコース、スポンサーライセンス、直紹介、浅い段の構成などの条件があります。</p><p>「その他 → 配置・育成順の候補を探す」で、メイン・サブをどの順にDRへ育てるか比較できます。「タイトル取得を目指すときの前提」を開くと、新規紹介IDの割当と、コース変更・ライセンス取得の予定を含めて計算できます。取得予定を含む案では購入費も変わります。</p><p>選んだ優先IDのLD・DRに必要な構成を先に埋め、DR取得の翌月から次のIDへ切り替えます。既存チームは自動移動しません。資格や紹介条件が足りなければ、その理由を表示します。</p><p>組織ページの「LD（試算）」は、仮配置と購入を反映した当月判定です。登録済みタイトルとは別で、条件を外せば表示も戻ります。</p></section>
    <section className="guide-section" id="guide-save"><p className="guide-eyebrow">04 · 残す</p><h2>よい案は「この案を保存」</h2><ol className="guide-steps"><li><strong>計算が終わったら「この案を保存」。</strong><span>配置を動かしただけでは自動保存されません。</span></li><li><strong>「その他 → 保存したプラン」から開く。</strong><span>保存時の入力・出発点・計算結果を見返せます。</span></li><li><strong>古い保存結果は、必要に応じて再計算。</strong><span>月別の組織図がない旧版では案内が出ます。元の保存結果は残ります。</span></li></ol><p>計画名、パートナー、成長率、コースなどは「その他 → 成長前提・サブ・詳細設定」から変更します。</p></section>
    <section className="guide-section"><details><summary>旧画面の操作画像（参考）</summary><p>以下は旧版の架空データの操作例です。現行版のボタン位置と操作名は、このガイド本文を参照してください。</p>{[["02-move","チームの移動"],["04-breakdown","ID別の報酬内訳"],["05-saved","保存プランの一覧"]].map(([file,caption])=><figure className="guide-screen" key={file}><a href={`/guide/${file}.png`} target="_blank" rel="noreferrer"><img src={`/guide/${file}.png`} alt={`旧画面の操作例：${caption}`} loading="lazy" width="1265" height="712"/></a><figcaption>旧画面：{caption}。画像の金額は操作例です。</figcaption></figure>)}</details></section>
    <NavLink className="guide-start" to="/simulator">配置を動かしてみる →</NavLink><footer className="guide-footer">Strategy Studio 2.4 対応 · 2026年9月更新</footer>
  </article>;
}
